image:
  repository: registry.gitlab.mavq.com/product/intellisuite/orca-server/orca-server/master
  tag: 9b90112ed939f689fe26777eca16b54eeb8f2c88
  pullPolicy: IfNotPresent

securityContext: false
fullnameOverride: "orca-server"

tolerations:
- key: pool
  operator: Equal
  value: e2-4c-16g
  effect: NoSchedule

imagePullSecrets:
  - name: gitlab-registry

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: pool
              operator: In
              values:
                - e2-4c-16g
            - key: environment
              operator: In
              values:
                - T2

serviceAccount:
  create: true
  name: "orca-server"

service:
  enabled: true
  type: ClusterIP
  port: 80
  containerPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: 'orca-server.dev.intellisuite.internal.mavq.io'
    paths:
      - path: /
        pathType: ImplementationSpecific

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  averageCPUUtilizationPercentage: 70
  averageMemoryUtilizationPercentage: 70

extraLabels:
  project: intellisuite
  team: intellisuite-orca-server
  customer: intellisuite

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi

configmaps:
  - appenv: true
    name: orca-server-config
    mountPath: /app/config/
    configData:
      config-postgres.properties: |
        # Servers.
        conductor.grpc-server.enabled=false

        # Database persistence type.
        conductor.db.type=postgres
        conductor.queue.type=redis_standalone
        conductor.redis.hosts=mavq-product-intellisuite-dev-redis-orca-master.mavq-product-intellisuite-dev-redis-orca.svc.cluster.local:6379:us-central1:xu3ISpi7IUYa4XOqMjg2S50kV83xoJ
        spring.datasource.url=jdbc:postgresql://10.50.0.3:5432/dev-intellisuite-orca-server
        spring.datasource.username=dev-intellisuite-orca-server
        spring.datasource.password=nPH0x8qQMPFka1BMp2tg6hmYHzAMsfc

        # Hikari pool sizes are -1 by default and prevent startup
        spring.datasource.hikari.maximum-pool-size=60
        spring.datasource.hikari.minimum-idle=5
        spring.datasource.hikari.idle-timeout=120000
        spring.datasource.hikari.max-lifetime=600000

        # Elastic search instance indexing is enabled.
        conductor.indexing.enabled=true
        conductor.indexing.type=postgres
        conductor.elasticsearch.version=postgres

        # Load sample kitchen sink workflow
        loadSample=false

secrets:
  - appenv: true
    name: orca-server-secret
    secretData:
      CONFIG_PROP: "config-postgres.properties"
